<<<<<<< HEAD
# Generated by Django 2.2.4 on 2019-09-26 05:35
=======
# Generated by Django 2.2.4 on 2019-10-04 01:08
>>>>>>> develope

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Like_movie',
            fields=[
                ('movieid', models.IntegerField(primary_key=True, serialize=False)),
                ('rank1', models.IntegerField(default=0)),
                ('rank2', models.IntegerField(default=0)),
                ('rank3', models.IntegerField(default=0)),
                ('rank4', models.IntegerField(default=0)),
                ('rank5', models.IntegerField(default=0)),
                ('rank6', models.IntegerField(default=0)),
                ('rank7', models.IntegerField(default=0)),
                ('rank8', models.IntegerField(default=0)),
                ('rank9', models.IntegerField(default=0)),
                ('rank10', models.IntegerField(default=0)),
=======
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
>>>>>>> develope
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.Movie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='M', max_length=10)),
                ('age', models.IntegerField(default=25)),
                ('occupation', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
