# Generated by Django 2.2.4 on 2019-10-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_based_movie',
            fields=[
                ('movieid', models.IntegerField(primary_key=True, serialize=False)),
                ('rank1', models.IntegerField(default=0)),
                ('rank2', models.IntegerField(default=0)),
                ('rank3', models.IntegerField(default=0)),
                ('rank4', models.IntegerField(default=0)),
                ('rank5', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='matrix_factorization_movie',
            fields=[
                ('movieid', models.IntegerField(primary_key=True, serialize=False)),
                ('rank1', models.IntegerField(default=0)),
                ('rank2', models.IntegerField(default=0)),
                ('rank3', models.IntegerField(default=0)),
                ('rank4', models.IntegerField(default=0)),
                ('rank5', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_based_movie',
            fields=[
                ('movieid', models.IntegerField(primary_key=True, serialize=False)),
                ('rank1', models.IntegerField(default=0)),
                ('rank2', models.IntegerField(default=0)),
                ('rank3', models.IntegerField(default=0)),
                ('rank4', models.IntegerField(default=0)),
                ('rank5', models.IntegerField(default=0)),
            ],
        ),
    ]
