# Generated by Django 2.2.4 on 2019-10-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_based_movie_matrix_factorization_movie_user_based_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_url',
            fields=[
                ('movieid', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
